name: my_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # K线图和指标管理（模仿富途）
  stock_charts:
    git:
      url: https://github.com/zxffffffff/stock-charts-dart.git
      ref: main
    # path: ../stock-charts-dart # 也可以指定本地路径

  # K线图和指标管理（模仿富途）
  note_editor:
    git:
      url: https://github.com/zxffffffff/note-editor.git
      ref: main
    # path: ../note-editor # 也可以指定本地路径

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
